// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArilxCT80I_pYUMBzfnBi7QV2noqnfbuE',
    appId: '1:762331191821:web:e221a7a93c6b7cc682d344',
    messagingSenderId: '762331191821',
    projectId: 'tingfm-c5dab',
    authDomain: 'tingfm-c5dab.firebaseapp.com',
    storageBucket: 'tingfm-c5dab.appspot.com',
    measurementId: 'G-WQ23Q1ECF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBszEXpePC1z55wZnH5gz_EM0Z--nTwFDs',
    appId: '1:762331191821:android:cca3676a0519b7a582d344',
    messagingSenderId: '762331191821',
    projectId: 'tingfm-c5dab',
    storageBucket: 'tingfm-c5dab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxADJqhfVjDTo4UQ-767cBqaQykV_VrbE',
    appId: '1:762331191821:ios:6e3e9dfb8bed75d882d344',
    messagingSenderId: '762331191821',
    projectId: 'tingfm-c5dab',
    storageBucket: 'tingfm-c5dab.appspot.com',
    androidClientId: '762331191821-pskdn0apsprk7vhb9ljnrdtp22phm5r9.apps.googleusercontent.com',
    iosClientId: '762331191821-srpus5ec3gjloh7rp4ldpap92q1rm55k.apps.googleusercontent.com',
    iosBundleId: 'com.mokanu.ant.tingfm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxADJqhfVjDTo4UQ-767cBqaQykV_VrbE',
    appId: '1:762331191821:ios:305c8fe754c5cc3182d344',
    messagingSenderId: '762331191821',
    projectId: 'tingfm-c5dab',
    storageBucket: 'tingfm-c5dab.appspot.com',
    androidClientId: '762331191821-pskdn0apsprk7vhb9ljnrdtp22phm5r9.apps.googleusercontent.com',
    iosClientId: '762331191821-fi9q1v8j5blr5r28rgh3181ktbk3geoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ting.RunnerTests',
  );
}
